import Navbar from './components/Navbar'
import Footer from './components/Footer'
import './MarketingPage.css'

export default function PrivacyPolicy() {
  return (
    <div className="mk">
      <Navbar />
      <main className="mk-legal">
        <div className="mk-container">
          <h1 className="mk-legal__title">Privacy Policy</h1>
          <p className="mk-legal__updated">Last updated: March 11, 2026</p>

          <p>
            This Privacy Policy describes how Artificial Enterprises, LLC ("Company," "we," "us," or "our")
            collects, uses, stores, shares, and otherwise processes your information when you access or use
            our services, applications, website, or any related products (collectively, the "Service").
            By accessing or using the Service in any manner, you unconditionally accept and consent to the
            practices described in this Privacy Policy. If you do not agree, you must immediately cease all
            use of the Service.
          </p>

          <h2>1. Information We Collect</h2>
          <p>
            We collect any and all information that you provide to us or that is generated through your use
            of the Service, including but not limited to:
          </p>
          <ul>
            <li>All inputs, prompts, messages, files, code, and content you submit to or through the Service</li>
            <li>All outputs, responses, and results generated by the Service in connection with your use</li>
            <li>Account and registration information (name, email, authentication credentials)</li>
            <li>Device information (hardware model, operating system, unique device identifiers, browser type and version)</li>
            <li>Usage data (features accessed, session duration, frequency of use, interaction patterns, click paths, keystrokes within the Service)</li>
            <li>Network and connection information (IP address, ISP, approximate geolocation)</li>
            <li>Cookies, tracking pixels, local storage, and similar technologies</li>
            <li>Any other information you voluntarily provide or that is automatically collected through your use of the Service</li>
          </ul>

          <h2>2. How We Use Your Information</h2>
          <p>
            We may use the information we collect for any lawful purpose at our sole discretion, including
            but not limited to:
          </p>
          <ul>
            <li>Providing, operating, maintaining, and improving the Service</li>
            <li>Training, fine-tuning, and improving our artificial intelligence models, algorithms, and technology</li>
            <li>Research, development, and creation of new products and services</li>
            <li>Marketing, advertising, and promotional purposes</li>
            <li>Analytics, benchmarking, and performance measurement</li>
            <li>Creating aggregate or de-identified datasets for any commercial purpose</li>
            <li>Enforcing our terms, policies, and legal rights</li>
            <li>Any other purpose we deem appropriate in our sole discretion</li>
          </ul>

          <h2>3. Data Sharing and Disclosure</h2>
          <p>
            We may share your information with any third party at our sole discretion, including but not limited to:
          </p>
          <ul>
            <li>Our affiliates, subsidiaries, parent companies, and related entities</li>
            <li>Service providers, contractors, and business partners</li>
            <li>Advertising and analytics partners</li>
            <li>Potential or actual acquirers, investors, or successors in connection with any merger, acquisition, financing, reorganization, or sale of assets</li>
            <li>Law enforcement, government agencies, or other third parties when we believe disclosure is necessary or appropriate</li>
            <li>Any other third party with or without your consent where permitted by applicable law</li>
          </ul>

          <h2>4. Data Retention</h2>
          <p>
            We retain your information indefinitely, or for as long as we deem necessary or useful for any
            purpose described in this Privacy Policy. We are under no obligation to delete, return, or
            cease using your information at any time, even after termination of your account or the Service.
            Deletion requests may be considered but are not guaranteed to be honored.
          </p>

          <h2>5. Data Security</h2>
          <p>
            While we may implement certain security measures, we make absolutely no warranties, representations,
            or guarantees regarding the security of your information. You acknowledge and agree that no method
            of electronic transmission or storage is 100% secure, and you transmit your information to us
            entirely at your own risk. We shall not be liable for any unauthorized access, breach, loss,
            or disclosure of your information.
          </p>

          <h2>6. Your Rights (or Lack Thereof)</h2>
          <p>
            To the maximum extent permitted by applicable law, you waive any and all rights to access, correct,
            delete, port, or restrict the processing of your information. Where such rights cannot be waived
            under mandatory applicable law, we will comply only to the minimum extent legally required.
            Any requests regarding your information may be directed to us, but we reserve the right to deny
            such requests where legally permissible.
          </p>

          <h2>7. Children's Privacy</h2>
          <p>
            The Service is not intended for use by individuals under the age of 18. We do not knowingly
            collect information from children under 18. If we become aware that we have collected information
            from a child under 18, we may, but are not obligated to, delete such information.
          </p>

          <h2>8. Third-Party Services</h2>
          <p>
            The Service may contain links to or integrations with third-party websites, services, or
            applications. We are not responsible for the privacy practices of any third party. Your
            interactions with third-party services are governed solely by those third parties' policies
            and terms.
          </p>

          <h2>9. Changes to This Privacy Policy</h2>
          <p>
            We may modify this Privacy Policy at any time, for any reason, without prior notice to you.
            Changes are effective immediately upon posting. Your continued use of the Service after any
            changes constitutes your acceptance of the updated Privacy Policy. It is your sole responsibility
            to review this Privacy Policy periodically.
          </p>

          <h2>10. Contact</h2>
          <p>
            If you have questions about this Privacy Policy, you may contact Artificial Enterprises, LLC.
            We are under no obligation to respond to inquiries within any specific timeframe.
          </p>

          <p className="mk-legal__disclaimer">
            &copy; {new Date().getFullYear()} Artificial Enterprises, LLC. All rights reserved.
          </p>
        </div>
      </main>
      <Footer />
    </div>
  )
}
